// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddAlbumHistory(albumID: string, albumName: string, itemsAdded: number, operation: string): $CancellablePromise<void> {
    return $Call.ByID(4274411820, albumID, albumName, itemsAdded, operation);
}

export function AddCredentials(newAuthString: string): $CancellablePromise<void> {
    return $Call.ByID(4083250689, newAuthString);
}

export function AddGoogleAccount(oauthToken: string): $CancellablePromise<string> {
    return $Call.ByID(733209449, oauthToken);
}

export function AddTokenBindingAliasFromADB(email: string): $CancellablePromise<void> {
    return $Call.ByID(3252041498, email);
}

export function CancelUploadRecordPreview(id: string): $CancellablePromise<void> {
    return $Call.ByID(2176132112, id);
}

/**
 * CountUploadCandidates uses the existing scanner without network requests.
 */
export function CountUploadCandidates(paths: string[]): $CancellablePromise<number> {
    return $Call.ByID(3619510350, paths);
}

export function CredentialNeedsTokenBinding(authString: string): $CancellablePromise<boolean> {
    return $Call.ByID(920629710, authString);
}

/**
 * ExportDebugLog writes a user-approved diagnostic report. Its contents are
 * prepared by the frontend without credentials or authentication tokens.
 */
export function ExportDebugLog(path: string, contents: string): $CancellablePromise<void> {
    return $Call.ByID(1110665643, path, contents);
}

/**
 * Export is streamed and excludes saved remote media keys and credentials.
 */
export function ExportUploadRecords(account: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2576368405, account, path);
}

export function ForgetUploadRecords(account: string, paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(2557007900, account, paths);
}

export function GetAccounts(): $CancellablePromise<$models.AccountsState> {
    return $Call.ByID(562122970).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAlbumAutoMode(): $CancellablePromise<boolean> {
    return $Call.ByID(492228705);
}

export function GetAlbumHistory(): $CancellablePromise<$models.AlbumHistoryEntry[]> {
    return $Call.ByID(1113957427).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetAlbumName(): $CancellablePromise<string> {
    return $Call.ByID(3590690922);
}

export function GetExcludePattern(): $CancellablePromise<string> {
    return $Call.ByID(2942848526);
}

/**
 * GetRecentAlbums returns the active account's recent album shortcuts. A copy
 * is returned so callers cannot mutate configuration without persistence.
 */
export function GetRecentAlbums(): $CancellablePromise<$models.RecentAlbum[]> {
    return $Call.ByID(461078137).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSettings(): $CancellablePromise<$models.Config> {
    return $Call.ByID(4262641511).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetUploadRecords(account: string, search: string, offset: number): $CancellablePromise<$models.UploadRecordPage> {
    return $Call.ByID(687878935, account, search, offset).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewAutoAlbums scans local sources without uploading or making API calls.
 */
export function PreviewAutoAlbums(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(1461498941, paths).then(($result: any) => {
        return $$createType7($result);
    });
}

export function PreviewUploadRecords(paths: string[], id: string): $CancellablePromise<$models.UploadRecordPreview> {
    return $Call.ByID(402473999, paths, id).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RemoveCredentials(email: string): $CancellablePromise<void> {
    return $Call.ByID(4243930372, email);
}

/**
 * RemoveRecentAlbum forgets a shortcut when its album key is no longer valid.
 */
export function RemoveRecentAlbum(albumID: string): $CancellablePromise<void> {
    return $Call.ByID(180472976, albumID);
}

export function SetAlbumAutoMode(autoMode: boolean): $CancellablePromise<void> {
    return $Call.ByID(1935381765, autoMode);
}

export function SetAlbumName(albumName: string): $CancellablePromise<void> {
    return $Call.ByID(841849854, albumName);
}

export function SetDeleteFromHost(deleteFromHost: boolean): $CancellablePromise<void> {
    return $Call.ByID(377345147, deleteFromHost);
}

export function SetDisableUnsupportedFilesFilter(disableUnsupportedFilesFilter: boolean): $CancellablePromise<void> {
    return $Call.ByID(821557574, disableUnsupportedFilesFilter);
}

export function SetExcludePattern(pattern: string): $CancellablePromise<void> {
    return $Call.ByID(4021766002, pattern);
}

export function SetForceUpload(forceUpload: boolean): $CancellablePromise<void> {
    return $Call.ByID(2189240988, forceUpload);
}

export function SetPairLivePhotos(pairLivePhotos: boolean): $CancellablePromise<void> {
    return $Call.ByID(3927958009, pairLivePhotos);
}

export function SetProxy(proxy: string): $CancellablePromise<void> {
    return $Call.ByID(2532528442, proxy);
}

export function SetRecordUploads(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1391173719, enabled);
}

export function SetRecursive(recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(455302378, recursive);
}

export function SetSaver(saver: boolean): $CancellablePromise<void> {
    return $Call.ByID(3030960747, saver);
}

export function SetSelected(email: string): $CancellablePromise<void> {
    return $Call.ByID(2816040807, email);
}

export function SetSetDateFromFilename(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(1731635347, v);
}

export function SetSkipIncompleteLivePhotos(skipIncompleteLivePhotos: boolean): $CancellablePromise<void> {
    return $Call.ByID(2521603022, skipIncompleteLivePhotos);
}

export function SetSkipRecordedUploads(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2707231733, enabled);
}

export function SetUpdateExistingPhotosToLive(updateExistingPhotosToLive: boolean): $CancellablePromise<void> {
    return $Call.ByID(3038371812, updateExistingPhotosToLive);
}

export function SetUploadThreads(uploadThreads: number): $CancellablePromise<void> {
    return $Call.ByID(1692245880, uploadThreads);
}

export function SetUseQuota(useQuota: boolean): $CancellablePromise<void> {
    return $Call.ByID(778544527, useQuota);
}

/**
 * TouchRecentAlbum records a successfully updated, explicitly selected album.
 * Auto Album folders are deliberately excluded by the caller to keep this
 * shortcut list useful instead of filling it with one-off folder albums.
 */
export function TouchRecentAlbum(albumID: string, albumName: string): $CancellablePromise<void> {
    return $Call.ByID(2984498577, albumID, albumName);
}

// Private type creation functions
const $$createType0 = $models.AccountsState.createFrom;
const $$createType1 = $models.AlbumHistoryEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.RecentAlbum.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Config.createFrom;
const $$createType6 = $models.UploadRecordPage.createFrom;
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = $models.UploadRecordPreview.createFrom;
