// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountSummary {
    "email": string;
    "needsTokenBinding": boolean;

    /** Creates a new AccountSummary instance. */
    constructor($$source: Partial<AccountSummary> = {}) {
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("needsTokenBinding" in $$source)) {
            this["needsTokenBinding"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountSummary($$parsedSource as Partial<AccountSummary>);
    }
}

export class AccountsState {
    "accounts": AccountSummary[];
    "selected": string;

    /** Creates a new AccountsState instance. */
    constructor($$source: Partial<AccountsState> = {}) {
        if (!("accounts" in $$source)) {
            this["accounts"] = [];
        }
        if (!("selected" in $$source)) {
            this["selected"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountsState instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountsState {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField0_0($$parsedSource["accounts"]);
        }
        return new AccountsState($$parsedSource as Partial<AccountsState>);
    }
}

/**
 * AlbumError represents an album creation error
 */
export class AlbumError {
    "AlbumName": string;
    "Error": string;

    /** Creates a new AlbumError instance. */
    constructor($$source: Partial<AlbumError> = {}) {
        if (!("AlbumName" in $$source)) {
            this["AlbumName"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumError instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumError($$parsedSource as Partial<AlbumError>);
    }
}

export class AlbumHistoryEntry {
    "albumId": string;
    "albumName": string;
    "itemsAdded": number;
    "operation": string;
    "createdAt": number;

    /** Creates a new AlbumHistoryEntry instance. */
    constructor($$source: Partial<AlbumHistoryEntry> = {}) {
        if (!("albumId" in $$source)) {
            this["albumId"] = "";
        }
        if (!("albumName" in $$source)) {
            this["albumName"] = "";
        }
        if (!("itemsAdded" in $$source)) {
            this["itemsAdded"] = 0;
        }
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumHistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumHistoryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumHistoryEntry($$parsedSource as Partial<AlbumHistoryEntry>);
    }
}

/**
 * AlbumStatus represents the status of album creation
 */
export class AlbumStatus {
    "AlbumName": string;
    "ItemsAdded": number;
    "TotalItems": number;
    "AlbumKeys": string[];
    "IsComplete": boolean;

    /** Creates a new AlbumStatus instance. */
    constructor($$source: Partial<AlbumStatus> = {}) {
        if (!("AlbumName" in $$source)) {
            this["AlbumName"] = "";
        }
        if (!("ItemsAdded" in $$source)) {
            this["ItemsAdded"] = 0;
        }
        if (!("TotalItems" in $$source)) {
            this["TotalItems"] = 0;
        }
        if (!("AlbumKeys" in $$source)) {
            this["AlbumKeys"] = [];
        }
        if (!("IsComplete" in $$source)) {
            this["IsComplete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumStatus {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AlbumKeys" in $$parsedSource) {
            $$parsedSource["AlbumKeys"] = $$createField3_0($$parsedSource["AlbumKeys"]);
        }
        return new AlbumStatus($$parsedSource as Partial<AlbumStatus>);
    }
}

export class Config {
    "recordUploads": boolean;
    "skipRecordedUploads": boolean;
    "credentials"?: string[];
    "selected": string;
    "proxy": string;
    "useQuota": boolean;
    "saver": boolean;
    "recursive": boolean;
    "forceUpload": boolean;
    "pairLivePhotos": boolean;
    "skipIncompleteLivePhotos": boolean;
    "updateExistingPhotosToLive": boolean;
    "uploadThreads": number;
    "deleteFromHost": boolean;
    "disableUnsupportedFilesFilter": boolean;
    "albumName": string;
    "albumAutoMode": boolean;
    "recentAlbumsByAccount"?: { [_ in string]?: RecentAlbum[] };
    "albumHistoryByAccount"?: { [_ in string]?: AlbumHistoryEntry[] };
    "setDateFromFilename": boolean;
    "excludePattern": string;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("recordUploads" in $$source)) {
            this["recordUploads"] = false;
        }
        if (!("skipRecordedUploads" in $$source)) {
            this["skipRecordedUploads"] = false;
        }
        if (!("selected" in $$source)) {
            this["selected"] = "";
        }
        if (!("proxy" in $$source)) {
            this["proxy"] = "";
        }
        if (!("useQuota" in $$source)) {
            this["useQuota"] = false;
        }
        if (!("saver" in $$source)) {
            this["saver"] = false;
        }
        if (!("recursive" in $$source)) {
            this["recursive"] = false;
        }
        if (!("forceUpload" in $$source)) {
            this["forceUpload"] = false;
        }
        if (!("pairLivePhotos" in $$source)) {
            this["pairLivePhotos"] = false;
        }
        if (!("skipIncompleteLivePhotos" in $$source)) {
            this["skipIncompleteLivePhotos"] = false;
        }
        if (!("updateExistingPhotosToLive" in $$source)) {
            this["updateExistingPhotosToLive"] = false;
        }
        if (!("uploadThreads" in $$source)) {
            this["uploadThreads"] = 0;
        }
        if (!("deleteFromHost" in $$source)) {
            this["deleteFromHost"] = false;
        }
        if (!("disableUnsupportedFilesFilter" in $$source)) {
            this["disableUnsupportedFilesFilter"] = false;
        }
        if (!("albumName" in $$source)) {
            this["albumName"] = "";
        }
        if (!("albumAutoMode" in $$source)) {
            this["albumAutoMode"] = false;
        }
        if (!("setDateFromFilename" in $$source)) {
            this["setDateFromFilename"] = false;
        }
        if (!("excludePattern" in $$source)) {
            this["excludePattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField2_0 = $$createType2;
        const $$createField17_0 = $$createType5;
        const $$createField18_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("credentials" in $$parsedSource) {
            $$parsedSource["credentials"] = $$createField2_0($$parsedSource["credentials"]);
        }
        if ("recentAlbumsByAccount" in $$parsedSource) {
            $$parsedSource["recentAlbumsByAccount"] = $$createField17_0($$parsedSource["recentAlbumsByAccount"]);
        }
        if ("albumHistoryByAccount" in $$parsedSource) {
            $$parsedSource["albumHistoryByAccount"] = $$createField18_0($$parsedSource["albumHistoryByAccount"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class FileUploadResult {
    "Cancelled": boolean;
    "MediaKey": string;
    "IsError": boolean;
    "IsLivePhoto": boolean;
    "Skipped": boolean;
    "SkipCode": string;
    "SkipReason": string;
    "ErrorMessage": string;
    "Path": string;
    "Paths": string[];

    /** Creates a new FileUploadResult instance. */
    constructor($$source: Partial<FileUploadResult> = {}) {
        if (!("Cancelled" in $$source)) {
            this["Cancelled"] = false;
        }
        if (!("MediaKey" in $$source)) {
            this["MediaKey"] = "";
        }
        if (!("IsError" in $$source)) {
            this["IsError"] = false;
        }
        if (!("IsLivePhoto" in $$source)) {
            this["IsLivePhoto"] = false;
        }
        if (!("Skipped" in $$source)) {
            this["Skipped"] = false;
        }
        if (!("SkipCode" in $$source)) {
            this["SkipCode"] = "";
        }
        if (!("SkipReason" in $$source)) {
            this["SkipReason"] = "";
        }
        if (!("ErrorMessage" in $$source)) {
            this["ErrorMessage"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Paths" in $$source)) {
            this["Paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileUploadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileUploadResult {
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Paths" in $$parsedSource) {
            $$parsedSource["Paths"] = $$createField9_0($$parsedSource["Paths"]);
        }
        return new FileUploadResult($$parsedSource as Partial<FileUploadResult>);
    }
}

/**
 * FilesDroppedEvent is emitted when files are dropped on any drop zone
 */
export class FilesDroppedEvent {
    "files": string[];
    "dropZone": string;

    /** Creates a new FilesDroppedEvent instance. */
    constructor($$source: Partial<FilesDroppedEvent> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("dropZone" in $$source)) {
            this["dropZone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilesDroppedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): FilesDroppedEvent {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new FilesDroppedEvent($$parsedSource as Partial<FilesDroppedEvent>);
    }
}

export class PreflightWarning {
    "Paths": string[];
    "Code": string;
    "Message": string;

    /** Creates a new PreflightWarning instance. */
    constructor($$source: Partial<PreflightWarning> = {}) {
        if (!("Paths" in $$source)) {
            this["Paths"] = [];
        }
        if (!("Code" in $$source)) {
            this["Code"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreflightWarning instance from a string or object.
     */
    static createFrom($$source: any = {}): PreflightWarning {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Paths" in $$parsedSource) {
            $$parsedSource["Paths"] = $$createField0_0($$parsedSource["Paths"]);
        }
        return new PreflightWarning($$parsedSource as Partial<PreflightWarning>);
    }
}

/**
 * RecentAlbum is a locally stored shortcut to an album that was successfully
 * updated by this app. AlbumID is the authoritative Google Photos album key.
 */
export class RecentAlbum {
    "albumId": string;
    "albumName": string;
    "lastUsedAt": number;

    /** Creates a new RecentAlbum instance. */
    constructor($$source: Partial<RecentAlbum> = {}) {
        if (!("albumId" in $$source)) {
            this["albumId"] = "";
        }
        if (!("albumName" in $$source)) {
            this["albumName"] = "";
        }
        if (!("lastUsedAt" in $$source)) {
            this["lastUsedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentAlbum instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentAlbum {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentAlbum($$parsedSource as Partial<RecentAlbum>);
    }
}

/**
 * StartUploadEvent is received from frontend to start upload
 */
export class StartUploadEvent {
    "files": string[];
    "bypassLocalRecords": boolean;

    /** Creates a new StartUploadEvent instance. */
    constructor($$source: Partial<StartUploadEvent> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("bypassLocalRecords" in $$source)) {
            this["bypassLocalRecords"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartUploadEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): StartUploadEvent {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new StartUploadEvent($$parsedSource as Partial<StartUploadEvent>);
    }
}

export class ThreadStatus {
    "WorkerID": number;

    /**
     * "idle", "hashing", "checking", "uploading", "finalizing", "completed", "skipped", "error"
     */
    "Status": string;
    "FilePath": string;
    "FileName": string;
    "Message": string;
    "BytesUploaded": number;
    "BytesTotal": number;

    /**
     * Current attempt number (1-based), 0 if not applicable
     */
    "Attempt": number;

    /** Creates a new ThreadStatus instance. */
    constructor($$source: Partial<ThreadStatus> = {}) {
        if (!("WorkerID" in $$source)) {
            this["WorkerID"] = 0;
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("FilePath" in $$source)) {
            this["FilePath"] = "";
        }
        if (!("FileName" in $$source)) {
            this["FileName"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("BytesUploaded" in $$source)) {
            this["BytesUploaded"] = 0;
        }
        if (!("BytesTotal" in $$source)) {
            this["BytesTotal"] = 0;
        }
        if (!("Attempt" in $$source)) {
            this["Attempt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreadStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadStatus($$parsedSource as Partial<ThreadStatus>);
    }
}

export class UploadBatchStart {
    "Total": number;
    "TotalBytes": number;
    "AlbumName": string;
    "AlbumAutoMode": boolean;
    "AutoAlbumFolders": string[];
    "WorkPaths": string[];

    /** Creates a new UploadBatchStart instance. */
    constructor($$source: Partial<UploadBatchStart> = {}) {
        if (!("Total" in $$source)) {
            this["Total"] = 0;
        }
        if (!("TotalBytes" in $$source)) {
            this["TotalBytes"] = 0;
        }
        if (!("AlbumName" in $$source)) {
            this["AlbumName"] = "";
        }
        if (!("AlbumAutoMode" in $$source)) {
            this["AlbumAutoMode"] = false;
        }
        if (!("AutoAlbumFolders" in $$source)) {
            this["AutoAlbumFolders"] = [];
        }
        if (!("WorkPaths" in $$source)) {
            this["WorkPaths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadBatchStart instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadBatchStart {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AutoAlbumFolders" in $$parsedSource) {
            $$parsedSource["AutoAlbumFolders"] = $$createField4_0($$parsedSource["AutoAlbumFolders"]);
        }
        if ("WorkPaths" in $$parsedSource) {
            $$parsedSource["WorkPaths"] = $$createField5_0($$parsedSource["WorkPaths"]);
        }
        return new UploadBatchStart($$parsedSource as Partial<UploadBatchStart>);
    }
}

export class UploadRecordPage {
    "rows": UploadRecordRow[];
    "hasMore": boolean;

    /** Creates a new UploadRecordPage instance. */
    constructor($$source: Partial<UploadRecordPage> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadRecordPage instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadRecordPage {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new UploadRecordPage($$parsedSource as Partial<UploadRecordPage>);
    }
}

export class UploadRecordPreview {
    "total": number;
    "matched": number;
    "usesAlbums": boolean;

    /** Creates a new UploadRecordPreview instance. */
    constructor($$source: Partial<UploadRecordPreview> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("matched" in $$source)) {
            this["matched"] = 0;
        }
        if (!("usesAlbums" in $$source)) {
            this["usesAlbums"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadRecordPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadRecordPreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadRecordPreview($$parsedSource as Partial<UploadRecordPreview>);
    }
}

export class UploadRecordRow {
    "path": string;
    "folder": string;
    "size": number;
    "recordedAt": string;
    "origin": string;

    /** Creates a new UploadRecordRow instance. */
    constructor($$source: Partial<UploadRecordRow> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("recordedAt" in $$source)) {
            this["recordedAt"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadRecordRow instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadRecordRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadRecordRow($$parsedSource as Partial<UploadRecordRow>);
    }
}

// Private type creation functions
const $$createType0 = AccountSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = RecentAlbum.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = AlbumHistoryEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = UploadRecordRow.createFrom;
const $$createType10 = $Create.Array($$createType9);
